# BML ASSIGNMENT -1 
## DATA PREPROCESSING

In [3]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [4]:
dataset = pd.read_csv("D:/BML/Stock_Market.csv.xls")
dataset

Date Symbol  Prev Close     Open     High      Low     Last  \
0    01-01-2018    TCS     2701.20  2682.30  2694.80  2635.00  2650.00   
1    02-01-2018    TCS     2645.60  2660.00  2669.60  2620.20      NaN   
2    03-01-2018    TCS     2631.20  2632.00      NaN  2631.20  2639.00   
3    04-01-2018    TCS     2638.65  2650.00  2662.00  2640.00  2650.00   
4    05-01-2018    TCS         NaN  2650.00  2699.50  2650.00  2695.00   
..          ...    ...         ...      ...      ...      ...      ...   
818  26-04-2021    TCS     3109.50  3102.05  3153.00  3088.05  3100.05   
819  27-04-2021    TCS     3100.80  3106.00  3136.10  3103.00  3132.75   
820  28-04-2021    TCS     3132.00  3149.95  3151.00  3112.00      NaN   
821  29-04-2021    TCS     3124.10  3145.60      NaN  3105.50  3114.45   
822  30-04-2021    TCS     3115.25  3099.00  3132.05  3020.00  3040.00   

       Close     VWAP     Volume      Turnover    Trades  Deliverable Volume  \
0    2645.60  2654.94   675880.0  1.794420e+14   19464.0            330691.0   
1    2631.20  2641.06   960145.0  2.535800e+14   46813.0            555820.0   
2    2638.65  2649.21   628560.0  1.665190e+14   32104.0            361072.0   
3    2657.10  2649.94   456541.0  1.209810e+14   32647.0            264561.0   
4    2689.20  2684.95   576853.0  1.548820e+14   30836.0            318083.0   
..       ...      ...        ...           ...       ...                 ...   
818  3100.80  3122.35  2490260.0  7.775460e+14       NaN           1345353.0   
819  3132.00  3122.18  1471417.0  4.594040e+14   97077.0            849767.0   
820  3124.10  3125.72  1639037.0           NaN   76017.0            847762.0   
821      NaN  3130.83  1621395.0  5.076310e+14   98275.0            837567.0   
822  3035.65  3063.19  3072305.0  9.411060e+14  157829.0           1942473.0   

     %Deliverble  
0         0.4893  
1         0.5789  
2         0.5744  
3         0.5795  
4         0.5514  
..           ...  
818       0.5402  
819       0.5775  
820       0.5172  
821       0.5166  
822       0.6323  

[823 rows x 14 columns]

# Splitting The Attributes Into Dependent And Independent:


## Independant Values

In [36]:
X = dataset.iloc[:,:-4].values
X

array([['01-01-2018', 'TCS', 2701.2, ..., 2645.6, 2654.94, 675880.0],
       ['04-01-2018', 'TCS', 2638.65, ..., 2657.1, 2649.94, 456541.0],
       ['19-01-2018', 'TCS', 2918.2, ..., 2959.3, 2930.77, 910000.0],
       ...,
       ['23-04-2021', 'TCS', 3118.8, ..., 3109.5, 3105.86, 1615309.0],
       ['27-04-2021', 'TCS', 3100.8, ..., 3132.0, 3122.18, 1471417.0],
       ['30-04-2021', 'TCS', 3115.25, ..., 3035.65, 3063.19, 3072305.0]],
      dtype=object)

## Dependant Values

In [33]:
Y = dataset.iloc[:,-4:].values
Y

array([[1.7944200e+14, 1.9464000e+04, 3.3069100e+05, 4.8930000e-01],
       [1.2098100e+14, 3.2647000e+04, 2.6456100e+05, 5.7950000e-01],
       [2.6670000e+14, 4.4039000e+04, 4.3695200e+05, 4.8020000e-01],
       [8.9651900e+14, 1.1151200e+05, 8.6238500e+05, 3.0680000e-01],
       [4.6589400e+14, 9.6721000e+04, 6.7380400e+05, 4.3620000e-01],
       [5.2773400e+14, 8.3526000e+04, 7.9657800e+05, 4.6000000e-01],
       [4.3955200e+14, 8.1638000e+04, 7.8574800e+05, 5.4980000e-01],
       [2.9200800e+14, 5.4736000e+04, 4.3765600e+05, 4.5640000e-01],
       [2.9449200e+14, 4.3364000e+04, 6.5591400e+05, 6.7210000e-01],
       [1.2700000e+16, 2.1613100e+05, 3.1556256e+07, 7.1660000e-01],
       [1.0200000e+15, 1.5106600e+05, 2.4879220e+06, 6.9130000e-01],
       [2.4021400e+14, 6.7851000e+04, 4.2843700e+05, 5.1530000e-01],
       [2.6685000e+14, 5.0519000e+04, 6.1992300e+05, 6.8520000e-01],
       [4.6673800e+14, 7.9572000e+04, 9.8214300e+05, 6.2870000e-01],
       [5.2263200e+14, 1.1947500e+

## Counting the missing values in the dataset


In [15]:
print(dataset.isnull().sum())

Date                  82
Symbol                 0
Prev Close            82
Open                  82
High                  82
Low                   82
Last                  82
Close                 82
VWAP                  82
Volume                82
Turnover              82
Trades                82
Deliverable Volume    82
%Deliverble           82
dtype: int64


## Dropping missing value records- remaining rows are kept as its place


In [17]:
dataset.dropna(inplace=True)
dataset

Date Symbol  Prev Close     Open     High      Low     Last  \
0    01-01-2018    TCS     2701.20  2682.30  2694.80  2635.00  2650.00   
3    04-01-2018    TCS     2638.65  2650.00  2662.00  2640.00  2650.00   
14   19-01-2018    TCS     2918.20  2930.55  2982.00  2903.65  2974.85   
17   24-01-2018    TCS     3102.00  3090.00  3259.05  3082.65  3174.95   
35   21-02-2018    TCS     2944.75  2974.00  3062.60  2960.05  3042.35   
..          ...    ...         ...      ...      ...      ...      ...   
801  26-03-2021    TCS     3064.85  3090.65  3118.00  3043.05  3062.00   
816  22-04-2021    TCS     3144.55  3148.00  3148.00  3105.25  3121.05   
817  23-04-2021    TCS     3118.80  3105.00  3119.00  3091.05  3110.20   
819  27-04-2021    TCS     3100.80  3106.00  3136.10  3103.00  3132.75   
822  30-04-2021    TCS     3115.25  3099.00  3132.05  3020.00  3040.00   

       Close     VWAP     Volume      Turnover    Trades  Deliverable Volume  \
0    2645.60  2654.94   675880.0  1.794420e+14   19464.0            330691.0   
3    2657.10  2649.94   456541.0  1.209810e+14   32647.0            264561.0   
14   2959.30  2930.77   910000.0  2.667000e+14   44039.0            436952.0   
17   3174.60  3189.59  2810769.0  8.965190e+14  111512.0            862385.0   
35   3042.30  3016.25  1544614.0  4.658940e+14   96721.0            673804.0   
..       ...      ...        ...           ...       ...                 ...   
801  3066.80  3078.97  3697370.0  1.138410e+15  201134.0           1512152.0   
816  3118.80  3122.39  1988980.0  6.210380e+14  172941.0           1191717.0   
817  3109.50  3105.86  1615309.0  5.016930e+14   93127.0            772358.0   
819  3132.00  3122.18  1471417.0  4.594040e+14   97077.0            849767.0   
822  3035.65  3063.19  3072305.0  9.411060e+14  157829.0           1942473.0   

     %Deliverble  
0         0.4893  
3         0.5795  
14        0.4802  
17        0.3068  
35        0.4362  
..           ...  
801       0.4090  
816       0.5992  
817       0.4781  
819       0.5775  
822       0.6323  

[196 rows x 14 columns]

In [18]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [22]:
imputer = imputer.fit(X[:,3:])

In [23]:
X[:,3:] = imputer.transform(X[:,3:])
X

array([['01-01-2018', 'TCS', 2701.2, ..., 2645.6, 2654.94, 675880.0],
       ['02-01-2018', 'TCS', 2645.6, ..., 2631.2, 2641.06, 960145.0],
       ['03-01-2018', 'TCS', 2631.2, ..., 2638.65, 2649.21, 628560.0],
       ...,
       ['28-04-2021', 'TCS', 3132.0, ..., 3124.1, 3125.72, 1639037.0],
       ['29-04-2021', 'TCS', 3124.1, ..., 2346.097975708502, 3130.83,
        1621395.0],
       ['30-04-2021', 'TCS', 3115.25, ..., 3035.65, 3063.19, 3072305.0]],
      dtype=object)

## Splitting the datatset into training and testing:

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=1)

In [28]:
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[['15-02-2021' 'TCS' nan ... 3139.85 3156.8 2630853.0]
 ['20-12-2018' 'TCS' 1968.45 ... 2346.097975708502 1955.65 1940277.0]
 ['05-11-2019' 'TCS' 2193.95 ... 2201.85 2187.98 2693475.0]
 ...
 ['18-04-2018' 'TCS' 3166.6 ... 3159.1 3166.57 1216533.0]
 ['14-12-2018' 'TCS' 1982.6 ... 2346.097975708502 1984.61 2473761.0]
 [nan 'TCS' 3050.2 ... 3075.8 3044.72 1681250.0]]
[['09-04-2019' 'TCS' 2070.75 ... 2091.5 2085.63 2690970.0]
 ['01-10-2018' 'TCS' 2183.7 ... 2255.55 2354.2876788124154 3772208.0]
 ['30-05-2018' 'TCS' 3523.5 ... 3514.1 3508.9 1889553.0]
 ...
 ['28-04-2020' 'TCS' 1836.6 ... 1859.05 1851.06 2678512.0]
 ['01-03-2019' 'TCS' 1983.45 ... 1995.4 1993.73 4148548.0]
 [nan 'TCS' 2888.95 ... 2918.2 2896.35 1104739.0]]
[[8.305070e+14          nan 1.214830e+06 4.618000e-01]
 [3.794510e+14 1.103300e+05 9.854570e+05 5.079000e-01]
 [5.893270e+14 1.365360e+05 1.572121e+06 5.837000e-01]
 ...
 [3.852230e+14 5.784600e+04          nan 5.542000e-01]
 [         nan          nan          nan 5.87000

## Feature scaling:

In [31]:
scaler = StandardScaler()
Y_train = scaler.fit_transform(Y_train)
Y_test = scaler.fit_transform(Y_test)
print(Y_train)
print(Y_test)

[[ 0.146337           nan -0.22083683 -0.2897646 ]
 [-0.53479173 -0.46206658 -0.36904588  0.11135728]
 [-0.21786307 -0.01095004  0.01002627  0.7709026 ]
 ...
 [-0.52607557 -1.36553911         nan  0.5142194 ]
 [        nan         nan         nan  0.79961631]
 [-0.33479276 -0.86978602 -0.54912428 -0.6499912 ]]
[[-3.94957842e-01 -3.10845215e-01 -5.32144985e-01 -7.94721491e-01]
 [ 4.20487719e-02  7.64982300e-01             nan  3.55218940e-01]
 [-2.38678094e-01 -2.76937433e-01 -4.37256584e-01             nan]
 [ 6.39250304e-01  1.83985351e+00  6.47815344e-01  4.14022712e-01]
 [ 2.56985436e-01  5.63134003e-01 -1.30488514e-01 -4.64766993e-01]
 [ 3.35540626e-01  1.12553596e+00  1.10981622e+00 -1.88383879e-02]
 [-7.15419840e-01             nan             nan -1.94432985e-01]
 [ 1.19820927e-01 -4.62364637e-01 -7.21083851e-01 -1.43502923e+00]
 [ 4.37903116e-01  4.54702874e-01  4.21727617e-01 -1.84632356e-01]
 [-6.15635022e-02 -3.27279969e-01  7.50670691e-02  6.31269981e-01]
 [-4.79510150e-01 